### ISSUE TITLE
Vein Miner and Grindstone

### ISSUE THREAD

**Issue by Uchi112** [LunaPixelStudios/Prominence#168] opened 2023-09-17 11:17 UTC
### Describe the Bug

The vein Miner enchant is not working 
also grind stones not letting me ripe the enchant to books 

### Reproduction Steps

1.
2.
3.
...

### Operating System

Windows 10

### Minecraft Version

1.19

### Modloader

Forge

### Modpack Version

Promenece II

### Optifine

I used Optifine

**Comment by nvb-uy** [comment] 2023-09-29 22:08
Duplicate of https://github.com/LunaPixelStudios/Prominence/issues/151 

Grindstone was disabled due to a dupe

**Closed by nvb-uy** 2023-09-29 22:08 UTC
Labels: bug, Forge, Optifine
