### ISSUE TITLE
Totem of Undying + 2-handed weapons cause server & client crash and deletion of totem of preservation!

### ISSUE THREAD

**Issue by InFuRiTy** [LunaPixelStudios/Prominence#23] opened 2023-05-27 00:02 UTC
### Describe the Bug

Equipping  a Totem of Undying and then wielding a 2-handed weapon creates a very bizarre scenario that causes both the server and client to hard crash  if something kills the player while having both items in both hands at the same time!

It has happened twice now while doing a village raid where a Legioner would deal ridiculous damage to me while i'm attacking him with a 2-handed weapon and a T.O.U in the off hand but it's disabled due to both my hands being full with said weapon.

Upon death a weird interaction must be occurring where the totem tries to trigger but can't due to being disabled from a heavy weapon wield.

Both server and client can't handle it resulting in a crash. Plus no Totem of Preservation is generated in both crashes resulting in me losing my whole inventory worth of items and gear!!

The 2 crashes happened in our comm. server and then i tested and confirmed it in SP too!!
I have not tested this with any other totems the pack offers though!!

EDIT--1--
The crash only occurs if the T.O.U is equipped in the shield slot instead of the Charm Slot, otherwise it functions as it's intended!

### Reproduction Steps

1. Launch game and create a SP world (don't do this in servers pls)
2.  Spawn in a Legioner or any other hostile mob
3. Equip yourself with a Totem of Undying  and a 2-handed weapon
4. Let the mob kill you while holding the weapon.
5. Crash!!
...
Disclaimer: The world file might become corrupted and/or unusable in many ways so pls test this in a new/test world which can be deleted afterwards!!

### Crash Report or Log

https://pastebin.com/bkBrHVnv

### Operating System

Windows 10 Pro

### Minecraft Version

1.19

### Modloader

Fabric

### Modpack Version

Prominence v1.6

### Optifine

No

### Other Mods

Inventory HUD+ 3.4.7 for 1.19.2 - Fabric

I use it for inventory and HUD elements management on screen to fit my playstyle.

**Comment by jmadarg** [comment] 2023-05-27 02:56
I think the crash is produced by the Charm feature of using totems from your inventory. Can you test if disabling it solves the issue?

**Comment by InFuRiTy** [comment] 2023-05-27 19:10
> I think the crash is produced by the Charm feature of using totems from your inventory. Can you test if disabling it solves the issue?

Ok so here is what i tested so far:

TEST 1
T.O.U + 2-handed weapon with Charm's TotemWorksFromInventory - ON.
Then a Mob damages the player until death.

T.O.U in any inventory slot - `Successful totem activation` - `Intended mod behavior` - `No crash`
T.O.U in the hotbar - `Successful totem activation` - `Intended mod behavior` - `No crash`
T.O.U in the Charm slot - `Successful totem activation` - `Intended mod behavior` - `No crash`
T.O.U in the Shield slot - `Unsuccessful/successful activation` (Limbo state)  - `Client/Server crash` - `Unintended mod behavior` - `Player dies and no Totem of Preservation is Created.` 

TEST 2
T.O.U + 2-handed weapon with Charm's TotemWorksFromInventory - OFF.
Then a Mob damages the player until death.

T.O.U in any inventory slot - `Unsuccessful totem activation` - `Intended mod behavior` - `No crash` - `Player dies and Totem of Preservation is Created` 
T.O.U in the hotbar - `Unsuccessful totem activation` - `Intended mod behavior` - `No crash` - `Player dies and Totem of Preservation is Created`
T.O.U in the Charm slot - `Successful totem activation` - `Intended mod behavior` - `No crash` 
T.O.U in the Shield slot -  `Unsuccessful totem activation` - `Intended mod behavior????` - `No crash` - `Player dies and Totem of Preservation is Created which includes the T.O.U that failed to activate`

That's all I had tested out so far...
Very weird behavior in this one.
I hope this helps sort things out and come up with a fix!!

**Comment by jmadarg** [comment] 2023-05-27 20:42
As far as I understand, you shouldn't be able to actually use/have something in off-hand while using a 2-handed weapon. BUT the crash is unexpected. Gonna ask the dev of Better Combat about this.
Thank you so much for your detailed testing! I really appreciate it!

**Comment by ZsoltMolnarrr** [comment] 2023-05-27 20:55
Hello!
There are so many factors at play here.
Nothing in the logs points specifically to Better Combat.
I was unable to reproduce such crash when Better Combat is installed on its own. I'm not sure how I could help.

**Comment by InFuRiTy** [comment] 2023-05-27 22:54
Is there anything else i can provide to help resolve this?

As far as i know this particular crash happens from Charm's TotemWorksFromInventory setting in conjunction with very specific equipped items and conditions. But it is a devastating one nonetheless!!

**Comment by nvb-uy** [comment] 2023-05-29 00:31
fixed in 1.6.1

**Closed by nvb-uy** 2023-05-29 00:31 UTC
Labels: bug, Fabric
